services:
  db:
    image: timescale/timescaledb:2.6.1-pg14
    env_file:
      - .env
    volumes:
      - db_volume_1:/var/lib/postgresql
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  grafana:
    image: grafana/grafana:8.5.2
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db

  mosquitto:
    image: eclipse-mosquitto:2.0.14
    ports:
      - 1881:1881
    volumes:
      - "./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"

  db-writer:
    image: db-writer:1.0
    env_file:
      - .env
    depends_on:
      - mosquitto
      - db

  api:
    image: ms-api:1.0
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db_volume_1: