services:
  db:
    image: "timescale/timescaledb:2.6.1-pg14"
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - 5432:5432

  grafana:
    image: "grafana/grafana"
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db

  mosquitto:
    image: "eclipse-mosquitto"
    ports:
      - 1881:1881
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "iam@admin.com"
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 5050:80
    depends_on:
      - db
  
  # db:
  #   image: "postgres"
  #   restart: "always"
  #   environment:
  #     POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  #     POSTGRES_USER: "${POSTGRES_USER}"
  #     POSTGRES_DB: "${POSTGRES_DB}"
  #   volumes:
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - "5432:5432"

  # web:
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
