apiVersion: 1

datasources:
  - name: "Timescale DB"
    type: "postgres"
    url: "$DATABASE_ADDRESS"
    user: "$DB_GRAFANA_USER"
    database: "$POSTGRES_DB"
    secureJsonData:
      password: "$DB_GRAFANA_PASSWORD"
    jsonData:
      postgresVersion: 1200
      timescaledb: true
      sslmode: "disable"
