apiVersion: 1

datasources:
  - name: "Timescale DB"
    type: "postgres"
    url: "$DATABASE_URL"
    user: "$GRAFANA_DB_USER"
    database: "$GRAFANA_DB_DB"
    secureJsonData:
      password: "$GRAFANA_DB_PASSWORD"
    jsonData:
      postgresVersion: 1200
      timescaledb: true
      sslmode: "disable"
