apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-writer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-db-writer
  template:
    metadata:
      labels:
        app: monitoring-db-writer
    spec:
      containers:
      - image: db-writer:1.0
        imagePullPolicy: Never
        name: db-writer
        # command:
        #   - "env"
        envFrom:
        - secretRef:
            name: env-secret
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
