apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-grafana
  template:
    metadata:
      labels:
        app: monitoring-grafana
    spec:
      securityContext:
        # runAsUser: 0
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
      - image: grafana/grafana:8.5.2
        name: grafana
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: env-secret
        resources:
          limits:
            cpu: 250m
            memory: 750Mi
        volumeMounts:
        - name: dashboards
          mountPath: /var/lib/grafana/dashboards/
        - name: provisioning
          mountPath: /etc/grafana/provisioning/    
      volumes:
      - name: dashboards
        configMap:
          name: grafana-configmap
          items:
          - key: "weather_dashboard.json"
            path: "weather_dashboard.json"
      - name: provisioning
        configMap:
          name: grafana-configmap
          items:
          - key: "default_dashboard.yaml"
            path: "dashboards/default_dashboard.yaml"
          - key: "timescale_db.yaml"
            path: "datasources/timescale_db.yaml"
    
