apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-configmap
data:
  mosquitto.conf: |
    persistence false
    log_dest stdout
    allow_anonymous true
    connection_messages true
    listener 1881
