{
 "title": "Weather dashboard",
 "time": { "from": "now-10d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device_id",
    "query": "select distinct device_id from sensor_data;"
   }
  ]
 },
 "panels": [
  {
   "title": "Maps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatures Map",
     "type": "geomap",
     "gridPos": { "h": 13, "w": 16, "x": 4, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  device_id,\n  avg(sensor_data.temp_c) AS value,\n  sensor_data.latitude AS latitude,\n  sensor_data.longitude AS longitude\nFROM sensor_data\nWHERE $__timeFilter(sensor_data.time) AND\n  device_id IN ($device_id)\nGROUP BY device_id, sensor_data.latitude, sensor_data.longitude;"
      }
     ]
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Average Temperatures Graph (Celsius)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT  \n  device_id,\n  time_bucket('1 day', time) AS time,\n  avg(temp_c)\nFROM sensor_data\nWHERE $__timeFilter(time) AND\n  sensor_data.device_id IN ($device_id)\nGROUP BY device_id, time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average Pressure Graph (hPa)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT  \n  device_id,\n  time_bucket('1 day', time) AS time,\n  avg(pressure_hpa)\nFROM sensor_data\nWHERE $__timeFilter(time) AND\n  sensor_data.device_id IN ($device_id)\nGROUP BY device_id, time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average Wind Speed Graph (m/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT  \n  device_id,\n  time_bucket('1 day', time) AS time,\n  avg(wind_speed_ms)\nFROM sensor_data\nWHERE $__timeFilter(time) AND\n  sensor_data.device_id IN ($device_id)\nGROUP BY device_id, time\nORDER BY time"
    }
   ]
  }
 ]
}